flipbit script: flip the gpio devices on/off. See Usage

diff --git a/BBB/flipbit b/BBB/flipbit
--- a/BBB/flipbit
+++ b/BBB/flipbit
@@ -2,14 +2,25 @@
 
 # Simple script to flip the gpio devices on/off
 
-device="/sys/devices/virtual/gpio/gpio$2/value"
+if [ $# != 1 ]; then
+  printf "Warning! Please be extremely careful running this script!\n"
+  printf "Usage: flipbit {GPIO #}\n"
+  printf "       flipbit 51\n"
+  exit 1;
+fi
 
-if [ -f device ]; then
+device="/sys/devices/virtual/gpio/gpio$1/value"
+
+if [ -f $device ]; then
   value=$(cat $device)
+
   if [ $value == 0 ]; then
     echo 1 > $device
   else 
     echo 0 > $device
   fi
+
+else
+  printf "error"
 fi
 
